---
title: "Geocode Stores"
author: "Ben Graft"
date: "11/10/2020"
output: html_document
---

### Load Libraries
```{r}
library(tidyverse)
library(purrr)
library(odbc)
library(RODBC)
library(dplyr)
library(ggplot2)
library(gtable)
library(stringi)
library(DBI)
library(naniar)
library(stringr)
library(lubridate)
library(maps)
library(readr)

con <- dbConnect(odbc::odbc(), dsn = "CLPImpala")

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, tidy = TRUE)

```

```{r}

df_geocode <- read_csv(file = "//data1/home/bi6ekbg/vipsam2/tdlinx_geocode.csv")

```

```{python}
import subprocess
import csv
import sys
def install(package):
    subprocess.check_call([sys.executable, "-m", "pip", "install", package])
def copy_subscripts(script):
    subprocess.check_call([sys.executable,"-m", script])

install('geopy')
```

```{python}

import csv
from time import sleep
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut

# Read in Dataframe containing TDLinx Number and Address for all Stores
df = r.df_geocode

# Geocode addresses
geolocator = Nominatim(user_agent="Chrome/86.0.4240.183")

with open('//data1/home/bi6ekbg/vipsam2/geocoded_address.csv','w') as f1:
    writer=csv.writer(f1, delimiter=',',lineterminator='\n',)
    writer.writerow(['tdlinx_number', 'address', 'latitude', 'longitude'])
    for row in df['store_address']:
        try:
            lat = geolocator.geocode(row, timeout = 60).latitude
        except:
            lat = 0
        sleep(1)
        try:
            lon = geolocator.geocode(row, timeout = 60).longitude
        except:
            lon = 0
        sleep(1)
        writer.writerow([row, lat, lon])
        print(row, lat, lon)


```
